Split pipeline in several steps

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -15,10 +15,9 @@ on:
     branches: [ "master" ]
 
 jobs:
-  build:
-
+  unit-tests:
+    name: Check unit tests
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 21
@@ -27,15 +26,79 @@ jobs:
         java-version: '21'
         distribution: 'temurin'
         cache: maven
-    - name: Run tests and coverage
-      run: mvn -B verify
-    - name: Generate JaCoCo Badge
-      uses: cicirello/jacoco-badge-generator@v2
+    - name: Run tests
+      run: mvn -B '-Dtest=!*IntegrationTest' verify -Djacoco.destFile=target/jacoco-fast.exec
+    - name: Upload jacoco exec results
+      uses: actions/upload-artifact@v2
       with:
-        generate-branches-badge: true
-    - name: Build with Maven
-      run: mvn -B package
+        name: unit-tests-jacoco
+        path: target/jacoco-fast.exec
 
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+  integration-tests:
+    name: Check integration tests
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up JDK 21
+      uses: actions/setup-java@v3
+      with:
+        java-version: '21'
+        distribution: 'temurin'
+        cache: maven
+    - name: Run tests
+      run: mvn -B '-Dtest=*IntegrationTest' verify -Djacoco.destFile=target/jacoco-slow.exec
+    - name: Upload jacoco exec results
+      uses: actions/upload-artifact@v2
+      with:
+        name: integration-tests-jacoco
+        path: target/jacoco-slow.exec
+
+  quality:
+    name: Verify quality
+    needs:
+      - unit-tests
+      - integration-tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 21
+        uses: actions/setup-java@v3
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+          cache: maven
+      - uses: actions/download-artifact@v2
+        with:
+          name: unit-tests-jacoco
+          path: target/
+      - uses: actions/download-artifact@v2
+        with:
+          name: integration-tests-jacoco
+          path: target/
+      - name: merge results
+        run: mvn jacoco:merge package jacoco:report verify -DskipTests=true
+      - name: Upload jacoco coverage despite the check result
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: coverage-results-report
+          path: target/site/jacoco/
+          if-no-files-found: error
+#      - name: Coverage
+#        run: |
+#          mvn -B jacoco:report -DskipTests
+#          COVERAGE=$(grep -Po 'instructions: \K[0-9.]+' ./target/site/jacoco/jacoco.xml)
+#          echo "Overall coverage is $COVERAGE%"
+#          if (( $(awk 'BEGIN {print ("'$COVERAGE'" >= 80)}') )); then
+#            echo "Overall coverage is below 80%"
+#            exit 1  # Set the pipeline status to failure
+#          fi
+      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
+      - name: Update dependency graph
+        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Build with Maven
+        run: mvn -B package
